# Generated by Django 6.0.2 on 2026-03-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egf_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='name1',
        ),
    ]
