# Generated by Django 6.0.2 on 2026-03-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egf_app', '0002_rename_name_address_name1'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='image',
            field=models.ImageField(default=None, upload_to='students/'),
            preserve_default=False,
        ),
    ]
