# Generated by Django 6.0.2 on 2026-03-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egf_app', '0003_address_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
