# Generated by Django 6.0.2 on 2026-03-07 05:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egf_app', '0004_alter_address_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
